h2-datasource:
  url: jdbc:h2:mem:jmpa_db;DB_CLOSE_DELAY=-1
  username: sa
  password:
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
